### ISSUE TITLE
Deprecation warnings on SASS processing

### ISSUE THREAD

**Issue by mihail-minkov** [foundation/foundation-sites#12617]
## What should happen?
The SASS to CSS processing should work without showing any errors.

## What happens instead?
It processes the changes I made to the SASS files, but in the process throws a bunch of deprecation errors, that slow the process considerably. From what I've seen most errors are related to `abs()`

Here's an example:
```
Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(33.3333333333%)
To emit a CSS abs() now: abs(#{33.3333333333%})
More info: https://sass-lang.com/d/abs-percent

   ╷
15 │   $dividend: abs($dividend);
   │              ^^^^^^^^^^^^^^
   ╵
    node_modules\motion-ui\src\util\_unit.scss 15:14                 divide()
    node_modules\motion-ui\src\util\_unit.scss 57:11                 strip-unit()
    node_modules\foundation-sites\scss\util\_math.scss 86:16         zf-parse-fraction()
    node_modules\foundation-sites\scss\util\_math.scss 132:12        fraction-to-percentage()
    node_modules\foundation-sites\scss\xy-grid\_cell.scss 61:11      xy-cell-size()
    node_modules\foundation-sites\scss\xy-grid\_cell.scss 95:40      xy-cell-size-css()
    node_modules\foundation-sites\scss\xy-grid\_cell.scss 165:11     xy-cell-size()
    node_modules\foundation-sites\scss\xy-grid\_cell.scss 240:5      xy-cell()
    node_modules\foundation-sites\scss\xy-grid\_layout.scss 34:5     xy-grid-layout()
    node_modules\foundation-sites\scss\xy-grid\_classes.scss 198:11  @content
    node_modules\foundation-sites\scss\util\_mixins.scss 276:5       @content
    node_modules\foundation-sites\scss\util\_mixins.scss 328:9       @content
    node_modules\foundation-sites\scss\util\_breakpoint.scss 171:7   breakpoint()
    node_modules\foundation-sites\scss\util\_mixins.scss 327:7       -zf-each-breakpoint-in()
    node_modules\foundation-sites\scss\util\_mixins.scss 275:3       -zf-each-breakpoint()
    node_modules\foundation-sites\scss\xy-grid\_classes.scss 195:5   xy-block-grid-classes()
    node_modules\foundation-sites\scss\xy-grid\_classes.scss 472:5   foundation-xy-grid-classes()
    scss\amg-socio.scss 13:1                                         root stylesheet

Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($s-pad, 3) or calc($s-pad / 3)

More info and automated migrator: https://sass-lang.com/d/slash-div
```

## Possible Solution
Change the code according to the new functions.

## Test Case and/or Steps to Reproduce (for bugs)
I just run `yarn start` in my foundation folder, and as soon as I do a SASS change I get these errors.

## Context
My package.json SASS related things are like this:
```
...
    "dependencies": {
        ...
        "foundation-sites": "^6.8.1",
        "motion-ui": "~2.0.0",
        "node-sass": "^9.0.0",
        "normalize.scss": "^0.1.0",
        "sass": "^1.69.5",
        ...
    },
    "devDependencies": {
        "autoprefixer": "^9.1.5",
        "browser-sync": "^2.18.13",
        "gulp": "^4.0.0",
        "gulp-load-plugins": "^2.0.7",
        "gulp-postcss": "^9.0.1",
        "gulp-sass": "^5.1.0",
        "postcss": "^8.3.11"
    },
...
```

My gulpfile SASS related things are like this:
```
const sassCompiler = require('gulp-sass')(require('sass'));

var folder = {
    nodestuff: 'node_modules',
    prejs: 'js',
    preimages: 'images',
    public_css: '../public/css',
    public_js: '../public/js',
    public_img: '../public/images'
};

var sassPaths = [
    folder.nodestuff + '/normalize.scss/scss',
    folder.nodestuff + '/foundation-sites/scss',
    folder.nodestuff + '/motion-ui/src'
];

function sass() {
    return gulp.src('scss/amg.scss')
        .pipe(sassCompiler({
                includePaths: sassPaths,
                outputStyle: 'compressed'
            })
            .on('error', sassCompiler.logError))
        .pipe($.postcss([
            autoprefixer({
                overrideBrowserslist: ['last 2 versions', 'ie >= 9']
            })
        ]))
        .pipe(gulp.dest(folder.public_css));
}
```

## Your Environment
- Foundation 6.8.1
- Node 18.8.2 with npm 9.8.1
- Yarn 4.0.2
- Windows 10 x64 22H2

## Checklist

- [x] I have read and follow the CONTRIBUTING.md document.
- [x] There are no other issues similar to this one.
- [x] The issue title and template are correctly filled.

**Comment by ErikKrause** [comment]
This deprecation warning was introduced with sass [1.65.0](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1650) on Aug 9, 2023

**Comment by ErikKrause** [comment]
> Is there a way to hide or silence these deprecation errors for the time being?

Use sass version [1.64.3](https://github.com/sass/dart-sass/releases/tag/1.64.2)

**Comment by mihail-minkov** [comment]
> > Is there a way to hide or silence these deprecation errors for the time being?
> 
> Use sass version [1.64.2](https://github.com/sass/dart-sass/releases/tag/1.64.2)

Isn't there a better solution for this? Isn't there something like a flag for yarn to ignore this kind of messages?

**Comment by kanow** [comment]
I would say, changing the code and use the recommendation from the deprecation message:
`To preserve current behavior: math.abs(33.3333333333%)`

**Comment by JoaquinPiersigilli** [comment]
Warnings still happen with both sass and foundation-sites at their latests versions.
Should be fixed in a minor release

**Comment by abetwothree** [comment]
Hi, just wondering if a new release version is planned to be tagged in the near future with the commits below that fix these warnings. Thank you!

https://github.com/foundation/foundation-sites/commit/c6e31f5ba440a8909ceb838a89083321f660f426
https://github.com/foundation/foundation-sites/commit/c2db616af8ab0071927c62c429ed3b1920dc62ba

**Comment by Netail** [comment]
Would love to know too @joeworkman :)

**Comment by joeworkman** [comment]
I am working with the Sass team in order to migrate off `@include` and over to `@use`.  It's a big deal. Maybe I should release what I already have done as an update first.

**Comment by Netail** [comment]
> I am working with the Sass team in order to migrate off `@include` and over to `@use`.  It's a big deal. Maybe I should release what I already have done as an update first. 

Oh nice! That would be awesome :D

**Comment by joeworkman** [comment]
Fixed in v6.9.0. Although the new `@use` will have to come in a later update. It's a pretty big change.

**Comment by simon449** [comment]
Hello there, 

I'm trying to make a custom foundation setup with GULP.
However, even with the latest v6.9.0 I still get alot of deprecation errors.

This is my gulfile.js (ignore the comments in dutch, its easy for me to see what it do's since im new to gulp):

const gulp = require('gulp');
const babel = require('gulp-babel');
const concat = require('gulp-concat');
const uglify = require('gulp-uglify');
const sourcemaps = require('gulp-sourcemaps');
const browserify = require('browserify');
const source = require('vinyl-source-stream');
const buffer = require('vinyl-buffer');
const sass = require('gulp-sass')(require('sass'));
const cleanCSS = require('gulp-clean-css');
const sourcemapsCSS = require('gulp-sourcemaps');

// Paden naar je JS- en SCSS-bestanden
const paths = {
  scripts: {
    src: './js/**/*.js', // main js file
    dest: './dist/js/'   // Output map voor JS
  },
  styles: {
    src: './scss/**/*.scss', // main scss file
    dest: './dist/css/'      // Output map voor CSS
  }
};

// Task: Scripts bundelen en transpileren
function scripts() {
  return browserify({
    entries: './js/app.js', // Je main script
    debug: true
  })
    .transform('babelify', { presets: ['@babel/preset-env'] }) // Babel transform
    .bundle()
    .pipe(source('bundle.js')) // Output als "bundle.js"
    .pipe(buffer())
    .pipe(sourcemaps.init({ loadMaps: true }))
    .pipe(uglify()) // Minify
    .pipe(sourcemaps.write('.')) // Sourcemaps
    .pipe(gulp.dest(paths.scripts.dest)); // Output map voor JS
}

// Task: SCSS compileren, minificeren en verplaatsen naar dist/css
function styles() {
  return gulp.src('./scss/app.scss') // Begin met de app.scss
    .pipe(sourcemaps.init()) // Initialiseer sourcemaps voor CSS
    .pipe(sass().on('error', sass.logError)) // Compileer SCSS naar CSS
    .pipe(cleanCSS()) // Minificeer de CSS
    .pipe(sourcemaps.write('.')) // Voeg sourcemaps toe
    .pipe(gulp.dest(paths.styles.dest)); // Output map voor CSS
}

// Task: Watcher voor zowel JS- als SCSS-bestanden
function watchFiles() {
  gulp.watch(paths.scripts.src, scripts); // Bewaak de JS-bestanden
  gulp.watch(paths.styles.src, styles);   // Bewaak de SCSS-bestanden
}

// Default Gulp task
exports.default = gulp.series(scripts, styles, watchFiles);

It gives around 315 repetitive deprecation warnings.
This is my package.json:

{
  "name": "testingfoundation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "license": "ISC",
  "scripts": {
    "gulp": "gulp"
  },
  "dependencies": {
    "foundation-sites": "^6.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.26.0",
    "@babel/preset-env": "^7.26.0",
    "babelify": "^10.0.0",
    "browserify": "^17.0.1",
    "gulp": "^5.0.0",
    "gulp-babel": "^8.0.0",
    "gulp-clean-css": "^4.3.0",
    "gulp-concat": "^2.6.1",
    "gulp-sass": "^6.0.0",
    "gulp-sourcemaps": "^3.0.0",
    "gulp-uglify": "^3.0.2",
    "sass": "^1.82.0",
    "vinyl-buffer": "^1.0.1",
    "vinyl-source-stream": "^2.0.0"
  }
}

With all these deprecation warnings (even with sass and foundation to the newest versions) it takes like 6 or 7 seconds to compile. Is there anything i'm missing?

I hope to hear from you! :)

Best regards,

Simon
